### ISSUE TITLE
Support scala 2.11.7

### ISSUE THREAD

**Issue by jendap** [scalatest/scalatest-eclipse-plugin#53]
The latest scala-ide for scala 2.11.7 throws exception ...

java.lang.ClassCastException: org.scalaide.core.internal.compiler.ScalaPresentationCompiler cannot be cast to scala.tools.nsc.interactive.CompilerControl
    at scala.tools.eclipse.scalatest.launching.ScalaTestLaunchShortcut$$anonfun$isScalaTestSuite$2.apply(ScalaTestLaunchShortcut.scala:195)
    at scala.tools.eclipse.scalatest.launching.ScalaTestLaunchShortcut$$anonfun$isScalaTestSuite$2.apply(ScalaTestLaunchShortcut.scala:190)
    at org.scalaide.core.internal.compiler.PresentationCompilerProxy$$anonfun$internal$1.apply(PresentationCompilerProxy.scala:105)
    at org.scalaide.core.internal.compiler.PresentationCompilerProxy$$anonfun$internal$1.apply(PresentationCompilerProxy.scala:104)
    at scala.Option.flatMap(Option.scala:171)
    at org.scalaide.core.internal.compiler.PresentationCompilerProxy.internal(PresentationCompilerProxy.scala:104)
    at org.scalaide.core.internal.compiler.PresentationCompilerProxy.apply(PresentationCompilerProxy.scala:62)
    at scala.tools.eclipse.scalatest.launching.ScalaTestLaunchShortcut$.isScalaTestSuite(ScalaTestLaunchShortcut.scala:190)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anonfun$1$$anonfun$apply$3$$anonfun$apply$4.apply(ScalaTestMainTab.scala:290)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anonfun$1$$anonfun$apply$3$$anonfun$apply$4.apply(ScalaTestMainTab.scala:289)
    at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anonfun$1$$anonfun$apply$3.apply(ScalaTestMainTab.scala:289)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anonfun$1$$anonfun$apply$3.apply(ScalaTestMainTab.scala:286)
    at scala.collection.TraversableLike$WithFilter$$anonfun$flatMap$2.apply(TraversableLike.scala:759)
    at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
    at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:758)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anonfun$1.apply(ScalaTestMainTab.scala:286)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anonfun$1.apply(ScalaTestMainTab.scala:285)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
    at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab.handleSearchButtonSelected(ScalaTestMainTab.scala:285)
    at scala.tools.eclipse.scalatest.launching.ScalaTestMainTab$$anon$5.widgetSelected(ScalaTestMainTab.scala:177)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)

**Comment by cheeseng** [comment]
@jendap I just rebuilt the plugin with scala 2.11.7 and uploaded it, hopefully it will be picked-up by scala-ide side soon (normally within 24 hours).

**Comment by jendap** [comment]
That was fast! Thank you @cheeseng!

**Comment by jendap** [comment]
Cool. It works in the main stable update site.

Thank you @cheeseng!
